project_name       = "acme"
owner              = "platform-team"
cost_center        = "engineering"
kubernetes_version = "1.33"
cidr_block         = "10.1.0.0/16"
service_ipv4_cidr  = "172.20.0.0/16"
